CREATE DATABASE CURSORES;
USE CURSORES;


CREATE TABLE VENDEDORES(
	IDVENDEDORE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	JAN INT,
	FEV INT,
	MAR INT

);


INSERT INTO VENDEDORES VALUES(NULL,'LEANDRO',3293,4948,40000);
INSERT INTO VENDEDORES VALUES(NULL,'CARLOS',4991,120,10000);
INSERT INTO VENDEDORES VALUES(NULL,'PEDRO',10293,333,30000);
INSERT INTO VENDEDORES VALUES(NULL,'LARISSA',4929,433,3000);
INSERT INTO VENDEDORES VALUES(NULL,'BIANCA',1092, 59034,60000);
INSERT INTO VENDEDORES VALUES(NULL,'GUILHERME',1399,939,1900);
INSERT INTO VENDEDORES VALUES(NULL,'JOÃO',13958,988,9580);
INSERT INTO VENDEDORES VALUES(NULL,'JOSE',4993,4848,41000);
INSERT INTO VENDEDORES VALUES(NULL,'MARIA',3909,5893,85000);



CREATE TABLE VENDA_TOTAL(
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT,
	TOTAL INT,
	MEDIA INT
);



DELIMITER  $

CREATE PROCEDURE INSEREDADOS()
BEGIN

	DECLARE FIM INT DEFAULT 0;
	DECLARE VAR1, VAR2, VAR3, V_TOTAL, V_MEDIA INT;
	DECLARE V_NOME VARCHAR(50);

	DECLARE REG CURSOR FOR (
		SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
	);

	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;

	OPEN REG;

	REPEAT
	
		FETCH REG INTO V_NOME, VAR1, VAR2, VAR3;
		IF NOT FIM THEN 
			
			SET V_TOTAL = VAR1 + VAR2 + VAR3;
			SET V_MEDIA = V_TOTAL / 3;

			INSERT INTO VENDA_TOTAL VALUES(V_NOME, VAR1, VAR2, VAR3, V_TOTAL, V_MEDIA);
		END IF;

	UNTIL FIM END REPEAT;

	CLOSE REG;

END
$

DELIMITER ;

CALL INSEREDADOS ();
