CREATE DATABASE comercio;

use comercio;

-- criando as tabelas

create table CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);



CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY (ID_CLIENTE) 
	REFERENCES CLIENTE(IDCLIENTE)
);



CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM','CEL')NOT NULL,
	NUMERO VARCHAR(15) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);



 -- colocando dados na tabela clientes

insert into cliente values(null,'João','M','joao@gmail.com','882818203');
insert into cliente values(null,'Guilherme','M','abacaximaldito@gmail.com','37247347378');
insert into cliente values (null,'Carlos','M','carlindomau@gmail.com','382347272'),
(null,'Bianca','F','bianquinhaboqueteparafuso@hotmail.com','382838458'),
(null,'larrisa','F','larrsinhafaztudo@hotmail.com','327837251'),
(null,'Poze do Rodo','M','mcpozedorodo@gmail.com','477281292'),
(null,'Lucas Domingos','M','omaismachodeagudos@gmail.com','482837182'),
(null,'Carla','F','carlapesodecaminhao@gmail.com','4812281821');
insert into cliente values(null,'Natyzinha','F','natyzinhamaldadepura@gmail.com','448718218');


-- colocando dados na tabela endereco 

insert into cliente values(null,'leozão','M','leolimpabem@gmail.com','323218218');
insert into endereco values(null,'Rua carlinhos maia','Vila andorinha','Agudos','SP',1);
insert into endereco values(null,'Rua cacete','Vila saco','Agudos','SP',2),
(null,'Rua bandeirantes','Rocinha','Rio de Janeiro','RJ',5),
(null,'Rua mooncock','Vila madalena','Bauru','SP',6),
(null,'Rua padre fábio de melo','Morro do alemão','boituva','SP',7),
(null,'Rua mamonas assasinas','Donald Trump','Maimi','FL',8),
(null,'Rua jair messias bolsonaro','Forças Armadas','Brasilia','DF',9),
(null,'Rua luis inácio lula da silva','Lava jato','Brasilia','DF',10),
(null,'Rua MC carol','Fode macacooo','terezina','PI',11),
(null,'Rua amaciante e parafusadeira','Hack','Rio branco','AC',12);


-- colocando dados na tabela telefone

insert into telefone values(null,'CEL','140992833',1)

insert into telefone values(null,'CEL','140232737',6),
(null,'RES','38483-3993',2),
(null,'COM','39304-3993',1),
(null,'CEL','149984303',10),
(null,'CEL','140334933',9),
(null,'COM','4002-8922',9),
(null,'CEL','149993030',7),
(null,'CEL','157773983',2);


SELECT nome, email, idcliente from cliente;

select id_cliente, bairro, cidade from endereco;

select nome, sexo, bairro, cidade /* projecao */
from cliente  /* ORIGEM */ 
	INNER JOIN endereco /*junção */
	on IDCLIENTE = ID_CLIENTE
where sexo = 'F'; /* seleção */ 


/* NOME, SEXO, EMAIL, TIPO, NUMERO */

SELECT nome, sexo, email, tipo, numero  
from cliente 
	inner join telefone 
	on idcliente = id_cliente
where nome = 'joão';

/* NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO */

select C.nome, C.sexo, E.bairro, E.cidade, T.tipo, T.numero
from cliente C
	inner join endereco E
	on C.IDCLIENTE = E.ID_CLIENTE
	inner join telefone T
	on C.IDCLIENTE = T.ID_CLIENTE;

select * from cliente
where idcliente = 8

/* exercicio  */ 

INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');

--

INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',13);
INSERT INTO ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',14);
INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',15);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',16);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',17);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',18);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',19);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',20);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',21);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',22);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',23);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',24);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',25);

--

INSERT INTO TELEFONE VALUES(NULL,'RES','68976565',13);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',13);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',15);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',15);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',15);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',12);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',13);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',22);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',16);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',17);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',18);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',19);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',20);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',20);


/* fazendo as querrys */

-- 1 EXERCICIO 
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF,
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO 
FROM CLIENTE C 
	INNER JOIN ENDERECO E
	on C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE F
	ON C.IDCLIENTE = F.ID_CLIENTE;

-- 2 EXERCICIO 
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF,
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO 
FROM CLIENTE C 
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T 
	ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF,
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, 
	   T.TIPO, T.NUMERO 
FROM CLIENTE C 
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T 
	ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';
-- 3 EXERCICIO
SELECT COUNT(*) AS QUANTIDADE, SEXO FROM CLIENTE 
GROUP BY SEXO;

-- 4 EXERCICIO
SELECT  C.NOME,C.IDCLIENTE, C.EMAIL, E.BAIRRO, T.TIPO FROM CLIENTE C
	INNER JOIN ENDERECO E 
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T 
	ON C.IDCLIENTE = T.ID_CLIENTE
	WHERE SEXO = 'F' AND BAIRRO = 'CENTRO' AND CIDADE = 'RIO DE JANEIRO' 
	AND (TIPO = 'RES' OR TIPO = 'COM');


-- EXERCICIO 5

SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR FROM CLIENTE C
	INNER JOIN ENDERECO E 
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
	WHERE ESTADO = 'RJ' AND TIPO = 'CEL';



-- EXERCICIO 6
SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T 
	ON C.IDCLIENTE = T.ID_CLIENTE
	WHERE SEXO = 'F' AND ESTADO = 'SP';
	

UPDATE CLIENTE SET SEXO = 'F' WHERE IDCLIENTE = 17;

SELECT * FROM CLIENTE WHERE IDCLIENTE = 17;

SELECT * FROM CLIENTE 
WHERE IDCLIENTE IN (12,13,14,15);



SELECT C.NOME, C.EMAIL, E.ESTADO, T.NUMERO 
FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE;




SELECT C.NOME, IFNULL(C.EMAIL, '**********') AS "EMAIL", E.ESTADO, T.NUMERO 
FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE;
	
SELECT C.NOME, C.SEXO, C.EMAIL, T.TIPO, T.NUMERO, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE;

CREATE VIEW RELATORIO AS
SELECT C.NOME, C.SEXO, C.EMAIL, T.TIPO, T.NUMERO, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE;

SELECT * FROM relatorio;



CREATE VIEW V_RELATORIO AS
SELECT C.NOME, C.SEXO, IFNULL(C.EMAIL,'CLIENTE SEM EMAIL') AS E-MAIL, T.TIPO, T.NUMERO, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE;

SELECT * FROM V_RELATORIO;

CREATE TABLE ALUNOS(
	NUMERO INT,
	NOME VARCHAR(30)
);
INSERT INTO ALUNOS VALUES(1,'JOAO'),
(1,'ANA'),
(2,'ZOE'),
(3,'CLARA'),
(2,'ANDRE'),
(1,'CLARA'),
(4,'LEANDRO'),
(5,'GUILHERME');


SELECT  * FROM ALUNOS 
ORDER BY NUMERO;


SELECT  * FROM ALUNOS 
ORDER BY 2;


SELECT * FROM v_relatorio ORDER BY 1;

/* PROCEDURES */

CREATE DATABASE PROJETO;

CREATE TABLE CURSOS(
		IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(30) NOT NULL,
		HORAS INT(3) NOT NULL,
		VALOR FLOAT(10,2) NOT NULL
); 




INSERT INTO CURSOS VALUES (NULL,'JAVA',30,500.00),
(NULL, 'FUNDAMENTO DE BANCO DE DADOS',40,700.00);

SELECT * FROM cursos;


DELIMITER $

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30), P_HORAS INT(3), P_VALOR FLOAT(10,2))
BEGIN 

	INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_VALOR);

END
$

DELIMITER ;

CALL CAD_CURSO('BI SQL SERVER',35,3000.00);
CALL CAD_CURSO('MONGODB',60,5000.00);
CALL CAD_CURSO('POWERBI',10,1000.00);
CALL CAD_CURSO('PYTHON',60,11000.00);
CALL CAD_CURSO('ORACLE',40,9000.00);
CALL CAD_CURSO('EXCEL',10,500.00);

/* CRIAR UMA PROCEDURE PARA CONSULTAR CURSOS */

CREATE TABLE VENDEDORES(
		IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(30) NOT NULL,
		SEXO CHAR(1) NOT NULL,
		JANEIRO FLOAT(10,2),
		FEVEREIRO FLOAT(10,2),
		MARCO FLOAT(10,2)
);

INSERT INTO VENDEDORES VALUES(NULL,'LEANDRO','M',100.00,6000.00,5000.00),
(NULL,'MARIA','F',300.00,200.00,100.00),
(NULL,'FABIO','M',4400.00,3000.00,200.00),
(NULL,'JULIA','F',1200.00,400.00,900.00),
(NULL,'EDUARDO','M',300.00,500.00,5300.00),
(NULL,'MONICA','F',100.00,100.00,1200.00),
(NULL,'CARLOS','M',1400.00,700.00,1100.00),
(NULL,'LIVIA','F',300.00,500.00,1000.00),
(NULL,'GUILHERME','M',100.00,600.00,2000.00);



SELECT * FROM vendedores;











